name: Generate and Deploy Site

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name: Prepare directories
        run: |
          echo "Creating necessary directories..."
          rm -rf docs
          mkdir -p docs/static/css
          mkdir -p logs
          echo "Setting permissions..."
          chmod -R 755 docs
          chmod -R 755 logs

      - name: Check directory structure
        run: |
          echo "Checking directory structure..."
          ls -la
          echo "Checking web directory..."
          ls -la web/
          echo "Checking templates..."
          ls -la web/templates/
          echo "Checking static files..."
          ls -la web/static/
          echo "Checking logs directory..."
          ls -la logs/
          echo "Checking docs directory..."
          ls -la docs/

      - name: Generate site
        run: |
          echo "Generating site..."
          python web/generate_site.py
          echo "Site generation completed"
          echo "Verifying generated files..."
          ls -la docs/
          echo "Contents of docs directory:"
          find docs/ -type f
          echo "Contents of index.html:"
          cat docs/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 